### ISSUE TITLE
Provide more insight into 10% vs 72.4% value

### ISSUE THREAD

**Issue by george-hawkins** [jwdunn1/CarND-PID-Parameter-Optimization#1]
Hello James - I stumbled across your repo when looking into Twiddle. I think it would be interesting and useful if you provided more context for this line in the README:

> In the discussion forum, Andres Castano observed in 2012, that the Twiddle algorithm might be improved some orders of magnitude simply by adjusting the increase/decrease amount from 10% to 72.4%.

I guess this is the same Andres who worked at the robotics division of NASA / JPL. I see he's posted other writeups (like this [one](http://www.acastano.com/others/udacity/cs_373_autonomous_car.html)) based on Udacity CS373 forum discussions. So I presume he'd have no objection to you do something similar and quoting his posts or the whole thread here for reference.

If moving from 10% to 72.4% leads to such an improvement to Twiddle, it'd be interesting to see a bit more explanation of why this is so - and perhaps some insight into why Sebastian Thrun might have missed this previously. 72.4% sounds very exact, i.e. not just some ball-park figure, it'd be interesting to know how Andres or you came up with this value.

**Comment by jwdunn1** [comment]
Hi George, in this repository, I've posted the referenced discussion from the Udacity forum. It provides an explanation of how the number 0.7237 was derived...by twiddling Twiddle. See the file: 2012-TwiddlingTwiddle-Castano.pdf

**Comment by george-hawkins** [comment]
Cool - thank you :slightly_smiling_face:
